name: basic_ads
description: "A Flutter Google Ads Package"
homepage: https://tguzel.dev
version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=3.24.0"


dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^5.2.0

dev_dependencies:
  basic_lint: ^1.0.0+1